### ISSUE TITLE
Only show weekdays in calendar

### ISSUE THREAD

**Issue by isocolon** [jiaweiteo/MockingJay12#11]
Improve data-ink ratio by only showing weekdays in the calendar.

**Comment by isocolon** [comment]
[Official API](https://fullcalendar.io/docs/businessHours) only supports de-emphasizing non-working days:

This can be done via the `businessHours` parameter in `calendar_options`:

```python
"businessHours": {
    "daysOfWeek": [1, 2, 3, 4, 5],
    "startTime": "09:00",
    "endTime": "18:00"
}
```

The outcome is like this - weekends in grey:
![image](https://github.com/user-attachments/assets/8be52a83-c864-4a1a-a02a-747d0390f904)

Workaround to suppress weekends entirely:

Add this to `custom_css`:

```css
th.fc-day-sun, th.fc-day-sat, td.fc-day-sun, td.fc-day-sat {
    display: none !important;
}
```

This gives the result we want:

![image](https://github.com/user-attachments/assets/89ddea52-43a4-4d77-9a83-0ea9402fae70)
